name: Create Functional Pearl discussion weekly

on:
  schedule:
    - cron: "0 12 * * 5" # 5 = Friday (12:00 UTC)
  workflow_dispatch:

jobs:
  create-discussion:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y jq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Test GraphQL perms
        run: |
          gh api graphql -f query='
            mutation($repo:ID!,$cat:ID!){
              createDiscussion(input:{
                repositoryId:$repo,
                categoryId:$cat,
                title:"Test",
                body:"test"
              }) { discussion { url } }
            }' -f repo="R_kgDOQdeRJA" -f cat="DIC_kwDOQdeRJM4CzEji"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a new GitHub Discussion
        id: create-discussion
        uses: abirismyname/create-discussion@main
        with:
          title: Feelings
          body: |
            Let's talk!
          github-token: ${{ secrets.GITHUB_TOKEN }}
